import Header from '@/components/Header';
import ClientProviders from '@/context/client-proviers';
import { ThemeProvider } from '@/context/theme-provider';
import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';

import './globals.css';

const fontType = Work_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClientProviders>
      <html lang='en'>
        <body className={fontType.className}>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClientProviders>
  );
}
